version: 0.0
os: linux
files:
  - source: index.jsp
    destination: /usr/share/tomcat8/webapps/sampleapp
  - source: WEB-INF
    destination: /usr/share/tomcat8/webapps/sampleapp/WEB-INF
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
    - location: scripts/cleanup
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
